name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_f2iMYerADmqyv18rmc0XfwxxQJPf/0A9Jg8Utlt"
